# Generated by Django 3.0 on 2020-08-23 18:40

from django.db import migrations
import xadmin_api.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20200822_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=xadmin_api.fields.ImageField(default='', help_text='$显示头像$', upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
