# Generated by Django 3.0 on 2020-08-23 18:40

from django.db import migrations, models
import xadmin_api.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200822_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.TextField(max_length=300, verbose_name='课程描述'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=xadmin_api.fields.ImageField(help_text='$显示图片$', upload_to='courses/%Y/%m', verbose_name='封面图'),
        ),
    ]
