# Generated by Django 3.0 on 2020-08-23 18:40

from django.db import migrations
import xadmin_api.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200822_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=xadmin_api.fields.ImageField(help_text='$显示图片$', upload_to='banner/%Y/%m', verbose_name='轮播图'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=xadmin_api.fields.ImageField(default='image/default.png', help_text='$显示头像$', upload_to='image/%Y/%m', verbose_name='头像'),
        ),
    ]
