# Generated by Django 3.1.2 on 2020-10-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletype',
            name='code',
            field=models.IntegerField(default=0, unique=True, verbose_name='文章code'),
        ),
    ]
