# Generated by Django 3.1.2 on 2020-10-07 21:40

from django.db import migrations
import xadmin_api_cli.fileds


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_auto_20201007_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='img',
            field=xadmin_api_cli.fileds.ImageField(default='', help_text='$显示图片$', max_length=255, upload_to='', verbose_name='封面图'),
        ),
    ]
